CONFIG=$1
HEADER=$2

echo "/* THIS FILE IS AUTOGENERATED             */" > $HEADER
echo "/* CHANGE .config INSTEAD OF THIS HEADER  */" >> $HEADER
echo ""                                 >> $HEADER
echo "#pragma once"                     >> $HEADER

for i in $(cat $CONFIG); do 
    CFG=(${i//=/ })
    if [ "${CFG[1]}" == "y" ]; then
        echo "#ifndef ${CFG[0]}" >> $HEADER
        echo "#define ${CFG[0]} 1" >> $HEADER
        echo "#endif" >> $HEADER
    fi
done